# Generated by Django 3.2.15 on 2023-02-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адреса клиентов',
            },
        ),
        migrations.CreateModel(
            name='AddressShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Адрес магазина',
                'verbose_name_plural': 'Адреса магазинов',
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
