# Generated by Django 3.2.15 on 2023-02-18 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_auto_20230219_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressclient',
            name='date_fill',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='addressshop',
            name='date_fill',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
