# Generated by Django 3.2.15 on 2023-02-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0003_auto_20230219_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressShop',
            new_name='AddressRestaurant',
        ),
        migrations.AlterModelOptions(
            name='addressrestaurant',
            options={'verbose_name': 'Адрес ресторана', 'verbose_name_plural': 'Адреса ресторанов'},
        ),
    ]
