# Generated by Django 3.2.15 on 2023-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0008_address_bad_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='bad_address',
            field=models.BooleanField(default=False, verbose_name='Рабочий ли адрес'),
        ),
    ]
