# Generated by Django 3.2.15 on 2023-02-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0009_alter_address_bad_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='bad_address',
        ),
    ]
