# Generated by Django 3.2.15 on 2023-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230218_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая сумма'),
        ),
    ]
