# Generated by Django 3.2.15 on 2023-02-18 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Согласован в'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Доставлен в'),
        ),
        migrations.AddField(
            model_name='order',
            name='register_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Зарегистрирован в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Contacting client', 'Необработан'), ('Packing order', 'Собирается'), ('Delivering order', 'В процессе доставки'), ('Successfully delivered', 'Доставлен')], db_index=True, default='Contacting client', max_length=256, verbose_name='Статус заказа'),
        ),
    ]
