# Generated by Django 3.2.15 on 2023-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_bad_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bad_address',
            field=models.BooleanField(default=False, verbose_name='Нерабочий ли адрес'),
        ),
    ]
