# Generated by Django 3.2.15 on 2023-03-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_bad_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bad_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Наличность'), ('Card', 'Карта')], db_index=True, max_length=25, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Contacting client', 'Необработан'), ('Packing order', 'Собирается'), ('Delivering order', 'В процессе доставки'), ('Successfully delivered', 'Доставлен')], db_index=True, default='Contacting client', max_length=25, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
